/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OXO;

/**
 *
 * @author SAGAR
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    int x[] = new int[20];
    int y[] = new int[20];
    int flag;
    public Main() {
        initComponents();
        for(int i=0;i<9;i++)
        {
            x[i] = 0;
            y[i] = 0;
        }
        flag = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText(" ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(170, 200, 80, 60);
        jDesktopPane2.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText(" ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(10, 200, 80, 60);
        jDesktopPane2.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText(" ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(90, 200, 80, 60);
        jDesktopPane2.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText(" ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(10, 140, 80, 60);
        jDesktopPane2.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText(" ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(90, 140, 80, 60);
        jDesktopPane2.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setText(" ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.setBounds(170, 140, 80, 60);
        jDesktopPane2.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton11.setText(" ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jButton11.setBounds(10, 80, 80, 60);
        jDesktopPane2.add(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton12.setText(" ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jButton12.setBounds(90, 80, 80, 60);
        jDesktopPane2.add(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton13.setText(" ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jButton13.setBounds(170, 80, 80, 60);
        jDesktopPane2.add(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setBackground(new java.awt.Color(102, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 2, 63));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Player 1");
        jLabel1.setBounds(10, 10, 240, 50);
        jDesktopPane2.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Retry");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(y[5]==0){
        if(flag==1)
        {
            jButton6.setText("X");
            x[5] = 1;
            y[5] = 1;
            flag++;
            jLabel1.setText("Player 2");
        }
        else
        {
            jButton6.setText("O");
            x[5] = 2;
            y[5] = 1;
            flag--;jLabel1.setText("Player 1");
        }
        
        check();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         if(y[1]==0){
        if(flag==1)
        {
            jButton11.setText("X");
            x[1] = 1;y[1] = 1;
            flag++;jLabel1.setText("Player 2");
        }
        else
        {
            jButton11.setText("O");
            x[1] = 2;y[1] = 1;
            flag--;jLabel1.setText("Player 1");
        }
        check();
         }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         if(y[2]==0){
        if(flag==1)
        {
            jButton12.setText("X");
            x[2] = 1;y[2] = 1;
            flag++;jLabel1.setText("Player 2");
            
        }
        else
        {
            jButton12.setText("O");
            x[2] = 2;y[2] = 1;
            flag--;jLabel1.setText("Player 1");
        }
        check();
         }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         if(y[3]==0){
        if(flag==1)
        {
            jButton13.setText("X");
            x[3] = 1;y[3] = 1;
            flag++;jLabel1.setText("Player 2");
        }
        else
        {
            jButton13.setText("O");
            x[3] = 2;y[3] = 1;
            flag--;jLabel1.setText("Player 1");
        }
        check();
         }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         if(y[4]==0){
        if(flag==1)
        {
            jButton5.setText("X");
            x[4] = 1;y[4] = 1;
            flag++;jLabel1.setText("Player 2");
        }
        else
        {
            jButton5.setText("O");
            x[4] = 2;y[4] = 1;
            flag--;jLabel1.setText("Player 1");
        }
        check();
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         if(y[6]==0){
        if(flag==1)
        {
            jButton7.setText("X");
            x[6] = 1;y[6] = 1;
            flag++;jLabel1.setText("Player 2");
        }
        else
        {
            jButton7.setText("O");
            x[6] = 2;y[6] = 1;
            flag--;jLabel1.setText("Player 1");
        }
        check();
         }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(y[7]==0){
        if(flag==1)
        {
            jButton2.setText("X");
            x[7] = 1;y[7] = 1;
            flag++;jLabel1.setText("Player 2");
        }
        else
        {
            jButton2.setText("O");
            x[7] = 2;y[7] = 1;
            flag--;jLabel1.setText("Player 1");
        }
        check();
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(y[8]==0){
        if(flag==1)
        {
            jButton4.setText("X");
            x[8] = 1;y[8] = 1;
            flag++;jLabel1.setText("Player 2");
        }
        else
        {
            jButton4.setText("O");
            x[8] = 2;y[8] = 1;
            flag--;jLabel1.setText("Player 1");
        }
        check();
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(y[9]==0){
        if(flag==1)
        {
            jButton1.setText("X");
            x[9] = 1;y[9] = 1;
            flag++;
        }
        else
        {
            jButton1.setText("O");
            x[9] = 2;y[9] = 1;
            flag--;
        }
        check();
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<9;i++)
        {
            x[i] = 0;
            y[i] = 0;
        }
        flag = 1;
        jLabel1.setText("Player 1");
        jButton1.setText(null);
        jButton11.setText(null);
        jButton12.setText(null);
        jButton13.setText(null);
        jButton2.setText(null);
        jButton5.setText(null);
        jButton6.setText(null);
        jButton7.setText(null);
        jButton4.setText(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    public void check()
    {
        if((x[1]==1 && x[2]==1 && x[3]==1 ) || (x[4]==1 && x[5]==1 && x[6]==1 ) || (x[7]==1 && x[8]==1 && x[9]==1 ))
            jLabel1.setText("Player 1 wins");
        if((x[1]==1 && x[4]==1 && x[7]==1 ) || (x[2]==1 && x[5]==1 && x[8]==1 ) || (x[3]==1 && x[6]==1 && x[9]==1 ))
            jLabel1.setText("Player 1 wins");
        if((x[1]==1 && x[5]==1 && x[9]==1 ) || (x[3]==1 && x[5]==1 && x[7]==1 ) )
             jLabel1.setText("Player 1 wins");
        if((x[1]==2 && x[2]==2 && x[3]==2 ) || (x[4]==2 && x[5]==2 && x[6]==2 ) || (x[7]==2 && x[8]==2 && x[9]==2 ))
            jLabel1.setText("Player 2 wins");
        if((x[1]==2 && x[4]==2 && x[7]==2 ) || (x[2]==2 && x[5]==2 && x[8]==2 ) || (x[3]==2 && x[6]==2 && x[9]==2 ))
            jLabel1.setText("Player 2 wins");
        if((x[1]==2 && x[5]==2 && x[9]==2 ) || (x[3]==2 && x[5]==2 && x[7]==2 ) )
             jLabel1.setText("Player 2 wins");
        for(int j = 1;j<=9;j++)
            if(y[j]==0)
                return;
        jLabel1.setText("Drawn");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
